com:
  storemgnmt:
    authentication: OAUTH2
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gigistore?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gigimuschi
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl:
        auto: none
      show_sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 59a641155b0f000d8b7c
            clientSecret: 0334101c37930ad541192ab4a2271b6f423ace9b


